
export default new Map([
["src/content/docs/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Findex.mdx&astroContentModuleFlag=true")],
["src/content/docs/atlas/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fatlas%2Findex.mdx&astroContentModuleFlag=true")],
["src/content/docs/atlas/justice.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fatlas%2Fjustice.mdx&astroContentModuleFlag=true")],
["src/content/docs/atlas/loyalty.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fatlas%2Floyalty.mdx&astroContentModuleFlag=true")],
["src/content/docs/essays/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fessays%2Findex.mdx&astroContentModuleFlag=true")],
["src/content/docs/fundamentals/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Ffundamentals%2Findex.mdx&astroContentModuleFlag=true")],
["src/content/docs/governance/canon governance.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fgovernance%2Fcanon+governance.mdx&astroContentModuleFlag=true")],
["src/content/docs/governance/canon-promotion-checklist.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fgovernance%2Fcanon-promotion-checklist.mdx&astroContentModuleFlag=true")],
["src/content/docs/governance/scope-boundaries.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fgovernance%2Fscope-boundaries.mdx&astroContentModuleFlag=true")],
["src/content/docs/fundamentals/laws/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Ffundamentals%2Flaws%2Findex.mdx&astroContentModuleFlag=true")],
["src/content/docs/fundamentals/laws/physical laws.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Ffundamentals%2Flaws%2Fphysical+laws.mdx&astroContentModuleFlag=true")],
["src/content/docs/fundamentals/laws/social.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Ffundamentals%2Flaws%2Fsocial.mdx&astroContentModuleFlag=true")],
["src/content/docs/fundamentals/laws/biological laws.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Ffundamentals%2Flaws%2Fbiological+laws.mdx&astroContentModuleFlag=true")],
["src/content/docs/fundamentals/laws/intellect laws.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Ffundamentals%2Flaws%2Fintellect+laws.mdx&astroContentModuleFlag=true")],
["src/content/docs/essays/circle-theory/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fessays%2Fcircle-theory%2Findex.mdx&astroContentModuleFlag=true")]]);
		